name: clang-format Check
on: [push]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        path:
          - include
          - data
          - courses
          - src
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: "18"
          check-path: ${{ matrix.path }}
          exclude-regex: "gbi.h"
